import Database from "better-sqlite3";
import path from "path";
import fs from "fs";

const DB_PATH = path.join(process.cwd(), "data", "max-planner.db");
const dataDir = path.dirname(DB_PATH);
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

const sqlite = new Database(DB_PATH);
sqlite.pragma("journal_mode = WAL");

sqlite.exec(`
  CREATE TABLE IF NOT EXISTS stations (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL
  );
`);

// Complete list from SNCF Open Data TGV Max dataset (331 stations)
const STATIONS = [
  { code: "FRMLW", name: "Aeroport Roissy CDG 2 TGV" },
  { code: "FRXAG", name: "Agde" },
  { code: "FRAGF", name: "Agen" },
  { code: "FRQAI", name: "Aime la Plagne" },
  { code: "FRAIE", name: "Aix en Provence TGV" },
  { code: "FRXAI", name: "Aix les Bains le Revard" },
  { code: "FRXAV", name: "Albertville" },
  { code: "FRAMA", name: "Albi Madeleine" },
  { code: "FRAFJ", name: "Albi Ville" },
  { code: "FRQAM", name: "Amiens" },
  { code: "FREFN", name: "Ancenis" },
  { code: "FRACL", name: "Angers Saint Laud" },
  { code: "FRANG", name: "Angouleme" },
  { code: "FRNCY", name: "Annecy" },
  { code: "FRQNJ", name: "Annemasse" },
  { code: "FRXAT", name: "Antibes" },
  { code: "FRXAC", name: "Arcachon" },
  { code: "FRARM", name: "Argeles sur Mer" },
  { code: "FRFMT", name: "Argenton sur Creuse" },
  { code: "FRHZA", name: "Arles" },
  { code: "FRQRV", name: "Arras" },
  { code: "FRARV", name: "Arvant" },
  { code: "FRFSD", name: "Assier" },
  { code: "FRFSQ", name: "Aubin" },
  { code: "DEAGB", name: "Augsburg HBF" },
  { code: "FRINC", name: "Aumont Aubrac" },
  { code: "FRXUY", name: "Auray" },
  { code: "FRAUR", name: "Aurillac" },
  { code: "FRFPW", name: "Auterive" },
  { code: "FRAES", name: "Avignon Centre" },
  { code: "FRAVG", name: "Avignon TGV" },
  { code: "FRXLT", name: "Ax les Thermes" },
  { code: "DEZCC", name: "Baden Baden" },
  { code: "FRINH", name: "Banassac la Canourgue" },
  { code: "FRXBU", name: "Banyuls sur Mer" },
  { code: "FRXBD", name: "Bar le Duc" },
  { code: "ESBST", name: "Barcelona Sants" },
  { code: "CHAJP", name: "Basel SBB" },
  { code: "FRXBY", name: "Bayonne" },
  { code: "FRXBV", name: "Beaune" },
  { code: "FRIMH", name: "Bedarieux" },
  { code: "FRTJA", name: "Belfort Montbeliard TGV" },
  { code: "FRXBF", name: "Bellegarde sur Valserine" },
  { code: "DEHBF", name: "Berlin HBF" },
  { code: "DEHBS", name: "Berlin Sudkreuz" },
  { code: "DEBGB", name: "Berlin-Gesundbrunnen" },
  { code: "FRTJB", name: "Besancon Franche Comte TGV" },
  { code: "FRABG", name: "Besancon Viotte" },
  { code: "FRXBH", name: "Bethune" },
  { code: "FRBZR", name: "Beziers" },
  { code: "FRBIQ", name: "Biarritz" },
  { code: "FRFAC", name: "Biganos Facture" },
  { code: "FRXBQ", name: "Blois Chambord" },
  { code: "FRBOJ", name: "Bordeaux Saint-Jean" },
  { code: "FRAEB", name: "Boulogne Ville" },
  { code: "FRXBK", name: "Bourg en Bresse" },
  { code: "FRQBM", name: "Bourg Saint Maurice" },
  { code: "FRBOU", name: "Bourges" },
  { code: "FRHLE", name: "Brassac les Mines Ste Florine" },
  { code: "FRBES", name: "Brest" },
  { code: "FRBXB", name: "Bretenoux Biars" },
  { code: "FRXBC", name: "Briancon" },
  { code: "FRBVE", name: "Brive la Gaillarde" },
  { code: "BEBMI", name: "Bruxelles Midi" },
  { code: "FRZAO", name: "Cahors" },
  { code: "FRSTH", name: "Calais Frethun" },
  { code: "FRINJ", name: "Campagnac St Geniez" },
  { code: "FRJCA", name: "Cannes" },
  { code: "FRCDC", name: "Capdenac" },
  { code: "FRCCF", name: "Carcassonne" },
  { code: "FRFWA", name: "Carmaux" },
  { code: "FRFTA", name: "Caussade" },
  { code: "FRIMC", name: "Ceilhes Roqueredonde" },
  { code: "FRXCE", name: "Cerbere" },
  { code: "FRXCD", name: "Chalon sur Saone" },
  { code: "FRXCR", name: "Chalons en Champagne" },
  { code: "FRCMF", name: "Chambery Challes les Eaux" },
  { code: "FREAH", name: "Champagne Ardenne TGV" },
  { code: "FRXCZ", name: "Charleville Mezieres" },
  { code: "FRQTJ", name: "Chartres" },
  { code: "FRCHR", name: "Chateauroux" },
  { code: "FRXCX", name: "Chatellerault" },
  { code: "FRIGS", name: "Chorges" },
  { code: "FRCFE", name: "Clermont Ferrand" },
  { code: "FRHTZ", name: "Cluses" },
  { code: "FRXCU", name: "Collioure" },
  { code: "FRAEJ", name: "Colmar" },
  { code: "FRBHA", name: "Commercy" },
  { code: "FRFSR", name: "Cransac" },
  { code: "FRCRE", name: "Crest" },
  { code: "FRCCY", name: "Culmont Chalindrey" },
  { code: "FRACG", name: "Dax" },
  { code: "FRDIE", name: "Die" },
  { code: "FRABA", name: "Dijon Ville" },
  { code: "FRDOL", name: "Dol de Bretagne" },
  { code: "FRACE", name: "Dole Ville" },
  { code: "FRXDN", name: "Douai" },
  { code: "FRADI", name: "Dunkerque" },
  { code: "FRIOG", name: "Elne" },
  { code: "FRIGV", name: "Embrun" },
  { code: "FREPL", name: "Epinal" },
  { code: "DEERF", name: "Erfurt HBF" },
  { code: "FRETA", name: "Etaples le Touquet" },
  { code: "FRXEB", name: "Evian les Bains" },
  { code: "FRFIG", name: "Figeac" },
  { code: "ESFIR", name: "Figueres Vilafant" },
  { code: "FRXFX", name: "Foix" },
  { code: "FRBQT", name: "Forbach" },
  { code: "DEFRS", name: "Frankfurt (Main) Sud" },
  { code: "DEFRH", name: "Frankfurt Am Main HBF" },
  { code: "FRFRA", name: "Frasne" },
  { code: "DEFGB", name: "Freiburg (Breisgau) HBF" },
  { code: "FRSHZ", name: "Fresnes Au Mont" },
  { code: "FRTGO", name: "Futuroscope" },
  { code: "FRGAT", name: "Gap" },
  { code: "CHGVA", name: "Geneve Cornavin" },
  { code: "ESGRO", name: "Girona" },
  { code: "FRFSI", name: "Gourdon" },
  { code: "FRFSB", name: "Gramat" },
  { code: "FRGNB", name: "Grenoble" },
  { code: "FRGGP", name: "Guingamp" },
  { code: "DEZHZ", name: "Halle (Saale) HBF" },
  { code: "FRHZK", name: "Hazebrouck" },
  { code: "FRAEF", name: "Hendaye" },
  { code: "FRXHE", name: "Hyeres" },
  { code: "FRHLB", name: "Issoire" },
  { code: "FRFMN", name: "Issoudun" },
  { code: "FREMR", name: "Jonzac" },
  { code: "FRJSY", name: "Juvisy" },
  { code: "DEKLT", name: "Kaiserslautern HBF" },
  { code: "DEQKA", name: "Karlsruhe HBF" },
  { code: "FRIHC", name: "L'Argentiere les Ecrins" },
  { code: "FRFQG", name: "L'Hospitalet pres l'Andorre" },
  { code: "FRJEE", name: "La Baule Escoublac" },
  { code: "FRXRO", name: "La Roche sur Yon" },
  { code: "FRLRH", name: "La Rochelle Ville" },
  { code: "FRLST", name: "La Souterraine" },
  { code: "FRFCJ", name: "La Teste" },
  { code: "DEANL", name: "Lahr Schwarzw" },
  { code: "FRLAM", name: "Lamballe" },
  { code: "FRXLD", name: "Landerneau" },
  { code: "FRHPG", name: "Landry" },
  { code: "FRLNZ", name: "Lannemezan" },
  { code: "FRLAI", name: "Lannion" },
  { code: "FRGBG", name: "Laroquebrou" },
  { code: "FRXTE", name: "Latour de Carol Enveitg" },
  { code: "CHAJF", name: "Lausanne" },
  { code: "FRACR", name: "Laval" },
  { code: "FRIMG", name: "Le Bousquet d'Orb" },
  { code: "FRXCC", name: "Le Creusot Montceau Montchanin" },
  { code: "FREGU", name: "Le Croisic" },
  { code: "FRAEZ", name: "Le Havre" },
  { code: "FRAET", name: "Le Mans" },
  { code: "FRLMR", name: "Le Monastier" },
  { code: "FREGS", name: "Le Pouliguen" },
  { code: "FRXLE", name: "Lens" },
  { code: "FRPFJ", name: "Lerouville Centre" },
  { code: "FRXRS", name: "Les Arcs Draguignan" },
  { code: "FRLAB", name: "Les Aubrais Orleans" },
  { code: "FRFQK", name: "Les Cabannes" },
  { code: "FRLSO", name: "Les Sables d'Olonne" },
  { code: "FRXLR", name: "Libourne" },
  { code: "FRADJ", name: "Lille Flandres" },
  { code: "FRLLE", name: "Lille Europe" },
  { code: "FRAGQ", name: "Limoges Benedictins" },
  { code: "FRLRT", name: "Lorient" },
  { code: "FREAM", name: "Lorraine TGV" },
  { code: "FRLDE", name: "Lourdes" },
  { code: "FRIFP", name: "Luc en Diois" },
  { code: "FRLCN", name: "Lucon" },
  { code: "FRLNE", name: "Luneville" },
  { code: "LULUX", name: "Luxembourg" },
  { code: "FRFQI", name: "Luzenac Garanou" },
  { code: "FRLPD", name: "Lyon Part-Dieu" },
  { code: "FRLPE", name: "Lyon Perrache" },
  { code: "FRJDQ", name: "Lyon St Exupery TGV" },
  { code: "FRMLT", name: "Macon Loche TGV" },
  { code: "FRHGU", name: "Macon Ville" },
  { code: "FRIMK", name: "Magalas" },
  { code: "DEMHG", name: "Mannheim HBF" },
  { code: "FRMTE", name: "Mantes la Jolie" },
  { code: "FRXMR", name: "Marmande" },
  { code: "FRMLV", name: "Marne la Vallee Chessy" },
  { code: "FRMBC", name: "Marseille Blancarde" },
  { code: "FRMSC", name: "Marseille Saint-Charles" },
  { code: "FRINE", name: "Marvejols" },
  { code: "FRHMY", name: "Massiac Blesle" },
  { code: "FRMPU", name: "Massy Palaiseau" },
  { code: "FRDJU", name: "Massy TGV" },
  { code: "FRFQH", name: "Merens les Vals" },
  { code: "FRADE", name: "Metz Ville" },
  { code: "FREAJ", name: "Meuse TGV" },
  { code: "ITMPG", name: "Milano Porta Garibaldi" },
  { code: "FRMAU", name: "Millau" },
  { code: "FRMAZ", name: "Miramas" },
  { code: "FRAGR", name: "Modane" },
  { code: "FRXMW", name: "Montauban Ville Bourbon" },
  { code: "FRGWE", name: "Montbard" },
  { code: "FRIGZ", name: "Montdauphin Guillestre" },
  { code: "FRXMK", name: "Montelimar" },
  { code: "FRMPL", name: "Montpellier Saint-Roch" },
  { code: "FRSUF", name: "Montpellier Sud de France" },
  { code: "FRMTJ", name: "Montrejeau Gourdan Polignan" },
  { code: "FRMXN", name: "Morlaix" },
  { code: "FRMCD", name: "Mouchard" },
  { code: "FRXMU", name: "Moulins sur Allier" },
  { code: "FRQMU", name: "Moutiers Salins Brides les Bains" },
  { code: "FRAEK", name: "Mulhouse Ville" },
  { code: "DEBEG", name: "Munchen HBF" },
  { code: "FRENC", name: "Nancy" },
  { code: "FRNTE", name: "Nantes" },
  { code: "FRXNA", name: "Narbonne" },
  { code: "FRFWF", name: "Naucelle" },
  { code: "FRNCH", name: "Neufchateau" },
  { code: "FRNEU", name: "Neussargues" },
  { code: "FRNVS", name: "Nevers" },
  { code: "FRNIC", name: "Nice Ville" },
  { code: "FRFNI", name: "Nimes Centre" },
  { code: "FRXZP", name: "Nimes Pont du Gard" },
  { code: "FRNIT", name: "Niort" },
  { code: "FRHQN", name: "Nurieux" },
  { code: "DEZPA", name: "Offenburg" },
  { code: "FRXOG", name: "Orange" },
  { code: "FRGFI", name: "Orthez" },
  { code: "ITOCS", name: "Oulx Cesana Sestriere" },
  { code: "FRPMS", name: "Pamiers" },
  { code: "FRPAZ", name: "Paris Austerlitz" },
  { code: "FRPBE", name: "Paris Bercy" },
  { code: "FRPLY", name: "Paris Gare de Lyon" },
  { code: "FRPMO", name: "Paris Gare du Nord" },
  { code: "FRPNO", name: "Paris Montparnasse" },
  { code: "FRPST", name: "Paris Gare de l'Est" },
  { code: "FRAEE", name: "Pau" },
  { code: "FRPGF", name: "Perpignan" },
  { code: "FRPFH", name: "Pierrefitte sur Aire" },
  { code: "FRPLT", name: "Plouaret Tregor" },
  { code: "FRPIS", name: "Poitiers" },
  { code: "FREGR", name: "Pornichet" },
  { code: "FRXPV", name: "Port Vendres Ville" },
  { code: "FRFQF", name: "Porte Puymorens" },
  { code: "FRUIP", name: "Quimper" },
  { code: "FRECO", name: "Quimperle" },
  { code: "FRCVU", name: "Rang du Fliers Verton Berck" },
  { code: "FRXRN", name: "Redon" },
  { code: "FRRHE", name: "Reims" },
  { code: "FRRNT", name: "Remiremont" },
  { code: "FRRNS", name: "Rennes" },
  { code: "FRBDT", name: "Rethel" },
  { code: "DERSH", name: "Ringsheim Europa Park" },
  { code: "FRRIO", name: "Riom Chatel Guyon" },
  { code: "FRRNE", name: "Roanne" },
  { code: "FRFSA", name: "Rocamadour Padirac" },
  { code: "FRRCO", name: "Rochefort" },
  { code: "FRRDZ", name: "Rodez" },
  { code: "FRRSP", name: "Rosporden" },
  { code: "FRURD", name: "Rouen Rive Droite" },
  { code: "DESBK", name: "Sarrebruck" },
  { code: "FRSAB", name: "Sable sur Sarthe" },
  { code: "FRSZE", name: "Saincaize" },
  { code: "FRHOJ", name: "Saint Avre la Chambre" },
  { code: "FRINB", name: "Saint Chely d'Apcher" },
  { code: "FRHHD", name: "Saint-Etienne Chateaucreux" },
  { code: "FRINM", name: "Saint Georges de Luzencon" },
  { code: "FRSGF", name: "Saint Germain des Fosses" },
  { code: "FRPFI", name: "Saint Mihiel" },
  { code: "FRSHY", name: "Saint Mihiel Detention" },
  { code: "FRXSJ", name: "Saint Quentin" },
  { code: "FRINN", name: "Saint Rome de Cernon" },
  { code: "FRXST", name: "Saintes" },
  { code: "FRXSN", name: "Sallanches Combloux Megeve" },
  { code: "FRSIA", name: "Sampigny Centre" },
  { code: "FRSBG", name: "Sarrebourg" },
  { code: "FRACN", name: "Saumur" },
  { code: "FRFPU", name: "Saverdun" },
  { code: "FRSNE", name: "Saverne" },
  { code: "FRXSW", name: "Sedan" },
  { code: "FRXSQ", name: "Selestat" },
  { code: "FRXSY", name: "Sete" },
  { code: "FRSVC", name: "Severac le Chateau" },
  { code: "FRSOU", name: "Souillac" },
  { code: "FRLPZ", name: "Souilly" },
  { code: "FRSBK", name: "Saint-Brieuc" },
  { code: "FRFST", name: "Saint Christophe" },
  { code: "FRSDM", name: "Saint Denis pres Martel" },
  { code: "FRXTD", name: "Saint Die" },
  { code: "FRIMW", name: "Saint Flour Chaudes Aigues" },
  { code: "FRFPH", name: "Saint Gaudens" },
  { code: "FRXGF", name: "Saint Gervais les Bains le Fayet" },
  { code: "FRXJZ", name: "Saint Jean de Luz Ciboure" },
  { code: "FRHPN", name: "Saint Jean de Maurienne Arvan" },
  { code: "FREJC", name: "Saint Maixent" },
  { code: "FRXSB", name: "Saint Malo" },
  { code: "FRXVR", name: "Saint Michel Valloire" },
  { code: "FRSNR", name: "Saint Nazaire" },
  { code: "FRXSH", name: "Saint Pierre des Corps" },
  { code: "FRXSK", name: "Saint Raphael Valescure" },
  { code: "FRGHA", name: "Saint Vincent de Tyrosse" },
  { code: "FRAEG", name: "Strasbourg" },
  { code: "DESGT", name: "Stuttgart HBF" },
  { code: "FREIP", name: "Surgeres" },
  { code: "FRFQM", name: "Tarascon sur Ariege" },
  { code: "FRXTB", name: "Tarbes" },
  { code: "FRTHP", name: "TGV Haute Picardie" },
  { code: "FRXTH", name: "Thionville" },
  { code: "FRXTS", name: "Thonon les Bains" },
  { code: "ITBGD", name: "Torino Porta Nuova" },
  { code: "ITTRS", name: "Torino Porta Susa" },
  { code: "FRTOL", name: "Toul" },
  { code: "FRTLN", name: "Toulon" },
  { code: "FRXYT", name: "Toulouse Matabiau" },
  { code: "FRADM", name: "Tourcoing" },
  { code: "FRINO", name: "Tournemire Roquefort" },
  { code: "FRAFW", name: "Tours" },
  { code: "DEQUL", name: "Ulm HBF" },
  { code: "FRAAW", name: "Uzerche" },
  { code: "FRVLA", name: "Valence TGV Rhone-Alpes" },
  { code: "FRVAF", name: "Valence Ville" },
  { code: "FRXVS", name: "Valenciennes" },
  { code: "CHAGL", name: "Vallorbe" },
  { code: "FRVNE", name: "Vannes" },
  { code: "FRESL", name: "Vendome Villiers sur Loir" },
  { code: "FRXVN", name: "Verdun" },
  { code: "FRDHT", name: "Versailles Chantiers" },
  { code: "FRVDY", name: "Veynes Devoluy" },
  { code: "FRVHY", name: "Vichy" },
  { code: "FRXVZ", name: "Vierzon" },
  { code: "FRXVT", name: "Vitre" },
  { code: "FRBFO", name: "Vitry le Francois" },
  { code: "FRVZD", name: "Viviez Decazeville" },
  { code: "CHAJD", name: "Zurich HB" },
];

const insert = sqlite.prepare(
  "INSERT OR REPLACE INTO stations (code, name) VALUES (?, ?)"
);

const insertMany = sqlite.transaction((stations: typeof STATIONS) => {
  for (const s of stations) {
    insert.run(s.code, s.name);
  }
});

insertMany(STATIONS);

console.log(`Seeded ${STATIONS.length} stations.`);
sqlite.close();
